
encryption_key: someRandomBINARYKEY
mailer:
  server: mail.example.com
  username: someLOGIN
  password: s0meth1ngs3cr3t
paypal:
  ip:         192.168.0.1
  login:      someLOGIN.yahoo.com
  password:   somePASSWORD
  signature:  someSIGNATURE
authnet:
  login:      <%= ENV['AUTHNET_LOGIN'] %>
  password:   <%= ENV['AUTHNET_PASSWORD'] %>
vat: false
require_state_in_address: true

# tax_per_state_id is a field for tax being applied at the state level or country wide level in "TaxRate model"
tax_per_state_id: true

uses_resque_for_background_emails: false

paperclip:
  s3_protocol: https
  s3_credentials:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  path: ':class/:attachment/:style/:hash.:extension'
  bucket: <%= ENV['FOG_DIRECTORY'] %>
  hash_secret: f8c07cf79094ec06f77b6024b5d7936c79b5227274fb8e82c00blaha
# Set this up with your Google Analytics Code for Devopment
google:
  analytics_code: false
